media: files/media

content:
  - name: posts
    label: Posts
    path: src/content
    type: collection
    view:
      fields: [date, title, description]
      primary: title
      sort: [date, title]
    fields:
      - name: id
        type: uuid
        required: true
      - name: date
        type: date
        required: true
      - name: title
        type: string
        required: true
      - name: body
        type: rich-text
        options:
          format: markdown

  - name: services
    path: src/data/services.json
    type: file
    list: true
    fields:
      - { name: id, type: uuid, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: published, label: Published, type: boolean, default: true }
      - { name: description, label: Description, type: string, required: true }
      - { name: body, label: Body, type: rich-text, required: true }
