media: files/media

content:
  - name: posts
    label: Posts
    path: src/content
    type: collection
    view:
      fields: [date, title, description]
      primary: title
      sort: [date, title]
    fields:
      - name: id
        type: uuid
        required: true
        hidden: true
      - name: date
        type: date
        required: true
      - name: title
        type: string
        required: true
      - name: body
        type: rich-text
        options:
          format: markdown
