media: files/media

content:
  - name: posts
    label: Posts
    path: src/content
    type: collection
    fields:
      - name: id
        label: ID
        type: uuid
        required: true
        hidden: true
      - name: title
        required: true
      - name: description
        label: Description
        type: string
